-- PostgreSQL schema for Supabase (Uredni Deska)

CREATE TABLE IF NOT EXISTS documents (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id          TEXT UNIQUE NOT NULL,
    kategorie       TEXT,
    nazev           TEXT,
    cj_zn           TEXT,
    vyveseni_dne    TEXT,
    sejmuti_dne     TEXT,
    popis           TEXT,
    poznamka        TEXT,
    zdroj           TEXT,
    first_seen_at   TIMESTAMPTZ DEFAULT NOW(),
    last_seen_at    TIMESTAMPTZ DEFAULT NOW(),
    removed_at      TIMESTAMPTZ,
    is_active       BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS document_versions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id          TEXT NOT NULL REFERENCES documents(doc_id) ON DELETE CASCADE,
    version         INTEGER NOT NULL,
    kategorie       TEXT,
    nazev           TEXT,
    cj_zn           TEXT,
    vyveseni_dne    TEXT,
    sejmuti_dne     TEXT,
    popis           TEXT,
    poznamka        TEXT,
    zdroj           TEXT,
    metadata_hash   TEXT NOT NULL,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS attachments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id          TEXT NOT NULL REFERENCES documents(doc_id) ON DELETE CASCADE,
    file_id         TEXT,
    file_name       TEXT NOT NULL,
    file_size       TEXT,
    file_description TEXT,
    download_url    TEXT,
    current_version INTEGER DEFAULT 1,
    first_seen_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS attachment_versions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attachment_id   BIGINT NOT NULL REFERENCES attachments(id) ON DELETE CASCADE,
    version         INTEGER NOT NULL,
    file_hash       TEXT NOT NULL,
    local_path      TEXT NOT NULL, -- Will store the path within Supabase Storage bucket
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS scrape_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id          TEXT NOT NULL,
    event_type      TEXT NOT NULL,
    doc_id          TEXT,
    message         TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS document_analyses (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id            TEXT UNIQUE NOT NULL REFERENCES documents(doc_id) ON DELETE CASCADE,
    severity          TEXT NOT NULL,
    summary           TEXT,
    is_analyzed_by_ai BOOLEAN DEFAULT FALSE,
    prompt_tokens     INTEGER DEFAULT 0,
    completion_tokens INTEGER DEFAULT 0,
    cost_czk          NUMERIC DEFAULT 0.0,
    model             TEXT,
    analyzed_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS weekly_summaries (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_start        DATE NOT NULL UNIQUE,
    week_end          DATE NOT NULL,
    summary_text      TEXT NOT NULL,
    doc_ids           JSONB DEFAULT '[]'::jsonb,
    prompt_tokens     INTEGER DEFAULT 0,
    completion_tokens INTEGER DEFAULT 0,
    cost_czk          NUMERIC DEFAULT 0.0,
    model             TEXT,
    created_at        TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_documents_doc_id ON documents(doc_id);
CREATE INDEX IF NOT EXISTS idx_documents_active ON documents(is_active);
CREATE INDEX IF NOT EXISTS idx_document_versions_doc_id ON document_versions(doc_id);
CREATE INDEX IF NOT EXISTS idx_attachments_doc_id ON attachments(doc_id);
CREATE INDEX IF NOT EXISTS idx_attachment_versions_att_id ON attachment_versions(attachment_id);
CREATE INDEX IF NOT EXISTS idx_scrape_log_run_id ON scrape_log(run_id);
CREATE INDEX IF NOT EXISTS idx_scrape_log_doc_id ON scrape_log(doc_id);

-- Custom function for sorting Czech dates 'D.M.YYYY'
CREATE OR REPLACE FUNCTION parse_date_cz(date_str TEXT) RETURNS DATE AS $$
DECLARE
    parts TEXT[];
BEGIN
    IF date_str IS NULL OR date_str = '' THEN
        RETURN NULL;
    END IF;
    parts := string_to_array(date_str, '.');
    IF array_length(parts, 1) = 3 THEN
        RETURN to_date(
            lpad(parts[1], 2, '0') || '-' || lpad(parts[2], 2, '0') || '-' || parts[3],
            'DD-MM-YYYY'
        );
    END IF;
    RETURN NULL;
EXCEPTION WHEN OTHERS THEN
    RETURN NULL;
END;
$$ LANGUAGE plpgsql IMMUTABLE;
